name: waterlens_lite
description: A GIS Flutter application.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  drift: ^2.30.0
  sqlite3_flutter_libs: ^0.5.41
  path_provider: ^2.1.5
  path: ^1.9.1
  image_picker: ^1.0.7
  file_picker: ^8.0.0
  excel: ^4.0.6

dev_dependencies:
  drift_dev: ^2.30.0
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
